# This workflow will deploy a specific build artifact into selected Azure App Services
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy To Azure App Services

run-name: ${{ format('Deploying {0} into Azure AppServices{1} {2}', (((github.event_name == 'repository_dispatch' && github.event.client_payload.is-pre-release) || (!startsWith(github.ref, 'refs/tags/v')) && '[Untagged Build]' || (github.event.client_payload.github.ref_name || github.ref_name)), ':', (github.event.client_payload.environment || inputs.environment)) }}

on:
  repository_dispatch:
    types: [new-deploy-artifacts-available]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to Deploy'
        type: environment
        default: 'B2B Dev'
        required: true
      artifacts-name:
        description: 'Artifacts'
        type: choice
        default: 'ZipDeployPackages'
        required: true
        options:
          - ZipDeployPackages
      deploy-to-webstore:
        description: 'Deploy to WebStore'
        type: boolean
        default: true
        required: true
      deploy-to-webportal:
        description: 'Deploy to WebPortal'
        type: boolean
        default: true
        required: true
      deploy-to-webservices:
        description: 'Deploy to WebServices'
        type: boolean
        default: true
        required: true
      deploy-to-webfeeds:
        description: 'Deploy to WebFeeds'
        type: boolean
        default: false
      deploy-to-webaccounts:
        description: 'Deploy to WebAccounts'
        type: boolean
        default: false

env:
  DEPLOYMENTS_WEBSTORE: false
  DEPLOYMENTS_WEBPORTAL: false
  DEPLOYMENTS_WEBSERVICES: false
  DEPLOYMENTS_WEBFEEDS: false
  DEPLOYMENTS_WEBACCOUNTS: false

jobs:
  environment-details:
    uses: ./.github/workflows/Environments.yml
    name: Set Environment Details
    with:
      environment-name: ${{ github.event.inputs.environment || github.event.client_payload.environment }}

  resolve-deploy-artifacts:
    runs-on: windows-latest
    name: Resolve Deployment Artifacts
    steps:

    - name: Download All Deployment Artifacts
      uses: dawidd6/action-download-artifact@v8
      with:
        github_token: ${{ secrets.FASTCHANNEL_MIRANDAASM_PAT }}
        workflow: Build.yml
        workflow_conclusion: success
        name: ${{ github.event.inputs.artifacts-name || github.event.client_payload.artifacts-name }}
        path: ./artifacts
    
    - name: '[DEBUG] List All Deployment Artifacts'
      working-directory: ./artifacts
      run: |
        Get-ChildItem -Path . -Recurse

    - name: Define Artifacts to Deploy
      run: |
        "DEPLOYMENTS_WEBSTORE=${{ inputs.deploy-to-webstore || github.event_name == 'repository_dispatch' }}" >> $env:GITHUB_ENV
        "DEPLOYMENTS_WEBPORTAL=${{ inputs.deploy-to-webportal || github.event_name == 'repository_dispatch' }}" >> $env:GITHUB_ENV
        "DEPLOYMENTS_WEBSERVICES=${{ inputs.deploy-to-webservices || github.event_name == 'repository_dispatch' }}" >> $env:GITHUB_ENV
        "DEPLOYMENTS_WEBFEEDS=${{ inputs.deploy-to-webfeeds || github.event_name == 'repository_dispatch' }}" >> $env:GITHUB_ENV
        "DEPLOYMENTS_WEBACCOUNTS=${{ inputs.deploy-to-webaccounts }}" >> $env:GITHUB_ENV

    - name: '[DEBUG] List Enabled Deployments'
      run: |
        $env:DEPLOYMENTS_WEBSTORE
        $env:DEPLOYMENTS_WEBPORTAL
        $env:DEPLOYMENTS_WEBSERVICES
        $env:DEPLOYMENTS_WEBFEEDS
        $env:DEPLOYMENTS_WEBACCOUNTS
  
    - name: Upload WebStore Deployment Artifact
      if: ${{ env.DEPLOYMENTS_WEBSTORE == 'true' }}
      uses: actions/upload-artifact@v4
      with:        
        name: webstore # Artifact name must match one of the 'appservice' Matrix names on the next job
        path: artifacts/fastchannel-webstore-zipdeploy.zip
        if-no-files-found: error
        compression-level: 0

    - name: Upload WebPortal Deployment Artifact
      if: ${{ env.DEPLOYMENTS_WEBPORTAL == 'true' }}
      uses: actions/upload-artifact@v4
      with:        
        name: manager # Artifact name must match one of the 'appservice' Matrix names on the next job
        path: artifacts/fastchannel-manager-zipdeploy.zip
        if-no-files-found: error
        compression-level: 0

    - name: Upload WebServices Deployment Artifact
      if: ${{ env.DEPLOYMENTS_WEBSERVICES == 'true' }}
      uses: actions/upload-artifact@v4
      with:        
        name: services # Artifact name must match one of the 'appservice' Matrix names on the next job
        path: artifacts/fastchannel-services-zipdeploy.zip
        if-no-files-found: error
        compression-level: 0

    - name: Upload WebFeeds Deployment Artifact
      if: ${{ env.DEPLOYMENTS_WEBFEEDS == 'true' }}
      uses: actions/upload-artifact@v4
      with:        
        name: feeds # Artifact name must match one of the 'appservice' Matrix names on the next job
        path: artifacts/fastchannel-feeds-zipdeploy.zip
        if-no-files-found: error
        compression-level: 0

    - name: Upload WebAccounts Deployment Artifact
      if: ${{ env.DEPLOYMENTS_WEBACCOUNTS == 'true' }}
      uses: actions/upload-artifact@v4
      with:        
        name: accounts # Artifact name must match one of the 'appservice' Matrix names on the next job
        path: artifacts/fastchannel-accounts-zipdeploy.zip
        if-no-files-found: error
        compression-level: 0

  appservice-deployment:
    needs: [environment-details, resolve-deploy-artifacts]
    name: Deploy ${{ env.APPSERVICE_NAME }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    if: >-
      ${{ (matrix.appservice == 'webstore' && env.DEPLOYMENTS_WEBSTORE == 'true') ||
          (matrix.appservice == 'manager'  && env.DEPLOYMENTS_WEBPORTAL == 'true') || 
          (matrix.appservice == 'services' && env.DEPLOYMENTS_WEBSERVICES == 'true') ||
          (matrix.appservice == 'feeds'    && env.DEPLOYMENTS_WEBFEEDS == 'true') ||
          (matrix.appservice == 'accounts' && env.DEPLOYMENTS_WEBACCOUNTS == 'true') }}
    strategy:
      fail-fast: false
      matrix:
        appservice: [webstore, manager, services, feeds, accounts]
        os: [windows-latest]
    
    environment:
      name: ${{ needs.environment-details.outputs.name }}
      url: ${{ needs.environment-details.outputs.url }}

    env:
      APPSERVICE_NAME: ${{ format('fastchannel-{0}-{1}', matrix.appservice, needs.environment-details.outputs.appservice-suffix) }}
      APPSERVICE_PACKAGE: ${{ github.workspace }}/artifacts/fastchannel-${{ matrix.appservice }}-zipdeploy.zip

    steps:
    - name: 'Download [${{ matrix.appservice }}] Artifact'
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true
        path: ./artifacts
        name: ${{ matrix.appservice }}

    - name: Login via Azure CLI
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy To Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.APPSERVICE_NAME }}
        package: ${{ env.APPSERVICE_PACKAGE }}

  cleanup-resources:
    needs: [appservice-deployment]
    name: Cleanup Resources
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    if: always()
    strategy:
      fail-fast: false
      matrix:
        appservice: [webstore, manager, services, feeds, accounts]
        os: [windows-latest]
    steps:
    - name: Cleanup Deployment Artifacts
      uses: geekyeggo/delete-artifact@v5
      with:
        name: ${{ matrix.appservice }}
